// <auto-generated />
using CfpExchange.Common.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CfpExchange.Migrations
{
    [DbContext(typeof(CfpContext))]
    [Migration("20180415182808_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CfpExchange.Models.Cfp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CfpAdded");

                    b.Property<DateTime>("CfpEndDate");

                    b.Property<DateTime>("CfpStartDate");

                    b.Property<string>("CfpUrl");

                    b.Property<int>("ClicksToCfpUrl");

                    b.Property<string>("EventDescription");

                    b.Property<DateTime>("EventEndDate");

                    b.Property<string>("EventImage");

                    b.Property<double>("EventLocationLat");

                    b.Property<double>("EventLocationLng");

                    b.Property<string>("EventLocationName");

                    b.Property<string>("EventName");

                    b.Property<DateTime>("EventStartDate");

                    b.Property<string>("EventUrl");

                    b.Property<string>("SubmittedByName");

                    b.Property<int>("Views");

                    b.HasKey("Id");

                    b.ToTable("Cfps");
                });
#pragma warning restore 612, 618
        }
    }
}
