pool:
  name: Azure Pipelines

variables:
 BuildConfiguration: 'release'
 BuildPlatform: 'any cpu'

stages:

- stage: Build
  jobs:

  - job: Build_Solution
    displayName: 'Build Solution'
    pool:
      vmImage: 'windows-2019'

    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Build CfpExchange'
      inputs:
        projects: '**/**.csproj'
        arguments: '--configuration $(BuildConfiguration) /p:platform="$(BuildPlatform)" /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation=$(build.artifactstagingdirectory)'

    - task: DotNetCoreCLI@2
      displayName: 'Run CfpExchange unit tests'
      inputs:
        command: test
        projects: '**/CfpExchange.Unittests/*.csproj'
        arguments: '--configuration $(BuildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)\TestResults\Coverage\ --collect "Code coverage"'

    - task: CopyFiles@2
      displayName: 'Copy Infrastructure Code'
      inputs:
        SourceFolder: 'Deployment'
        Contents: |
          **/*.ps1
          **/*.json
        TargetFolder: '$(build.artifactstagingdirectory)/Deployment'
        flattenFolders: true

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
