name: Build CfpExchange
env:
  TEST_RESULTS_FOLDER: '$HOME/TEST_RESULTS/'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Build
      run: dotnet build --configuration Release
    - name: Run Common tests
      run: dotnet test CfpExchange.Common.UnitTests --collect:"XPlat Code Coverage" --results-directory $TEST_RESULTS_FOLDER
    - name: Run Services tests
      run: dotnet test CfpExchange.Common.Services.UnitTests --collect:"XPlat Code Coverage" --results-directory $TEST_RESULTS_FOLDER
    - name: Run CfpExchange tests
      run: dotnet test CfpExchange.Unittests --collect:"XPlat Code Coverage" --results-directory $TEST_RESULTS_FOLDER
    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@4.6.4
      with:
        reports: '${{ env.TEST_RESULTS_FOLDER }}*'
        targetdir: '${{ env.TEST_RESULTS_FOLDER }}'
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.1.4
      with:
        # Artifact name
        name: Testreport
        # A file, directory or wildcard pattern that describes what to upload
        path: '${{ env.TEST_RESULTS_FOLDER }}*.html'
